trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CheckoutSCM
  jobs:
  - job: Checkout
    steps:
    - script: echo Checking out!

- stage: GitWorkFlow
  jobs:
  - job: Workflow
    steps:
    - script: echo Workflow!
  
- stage: UnitTests
  jobs:
  - job: TestOnWindows
    steps:
      - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
      - script: echo Testing on Linux!

- stage: Publish
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!

- stage: PostActions
  jobs:
  - job: Actions
    steps:
    - script: echo Actions!