trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CheckoutSCM
  displayName: 'Checkout SCM'
  jobs:
  - job: Checkout
    timeoutInMinutes: 1
    steps:
    - script: echo Checking out!

- stage: GitWorkFlow
  displayName: 'Git Workflow'
  jobs:
  - job: Workflow
    displayName: 'Checkout SCM'
    timeoutInMinutes: 1
    steps:
    - script: echo Workflow!
  
- stage: UnitTests
  displayName: 'Unit Tests'
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it
  jobs:
  - job: TestWin
    displayName: 'Test on Windows'
    
    timeoutInMinutes: 1
    steps:
      - script: echo Testing on Windows!
  - job: TestLin
    displayName: 'Test on Linux'
    timeoutInMinutes: 1
    steps:
      - script: echo Testing on Linux!
  - job: TestMac
    displayName: 'Test on Mac'
    timeoutInMinutes: 1
    steps:
      - script: echo Testing on Mac!

- stage: Publish
  jobs:
  - job: Deploy
    timeoutInMinutes: 1
    steps:
    - script: echo Deploying the code!

- stage: PostActions
  displayName: 'Post Actions'
  jobs:
  - job: Actions
    timeoutInMinutes: 1
    steps:
    - script: echo Actions!